// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Request.Infrastructure;

namespace Request.Infrastructure.Migrations
{
    [DbContext(typeof(RequestContext))]
    partial class RequestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:request.permissionseq", "'permissionseq', 'request', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:request.permissiontypeseq", "'permissiontypeseq', 'request', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Request.Domain.AggregatesModel.Permission.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "permissionseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "request")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("_employeeLastName")
                        .IsRequired()
                        .HasColumnName("EmployeeLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_employeeName")
                        .IsRequired()
                        .HasColumnName("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("_permissionDate")
                        .IsRequired()
                        .HasColumnName("PermissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("_permissionTypeId")
                        .IsRequired()
                        .HasColumnName("PermissionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_permissionTypeId");

                    b.ToTable("Permission","request");
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.Permission.PermissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "permissiontypeseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "request")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("_description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionType","request");
                });

            modelBuilder.Entity("Request.Domain.AggregatesModel.Permission.Permission", b =>
                {
                    b.HasOne("Request.Domain.AggregatesModel.Permission.PermissionType", "PermissionType")
                        .WithMany()
                        .HasForeignKey("_permissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
